In [1]:
import pandas as pd
from math import ceil

import requests
from bs4 import BeautifulSoup
import time
from time import sleep
# import numpy as np

In [2]:
cafe_id = pd.read_csv('cafe_id.csv')

In [10]:
cafe_id.head(10)

   Unnamed: 0           0
0           0    13615194
1           1   890539012
2           2   712442596
3           3   661112233
4           4  1811558348
5           5  1166368101
6           6    17358222
7           7    24347146
8           8  1844506916
9           9    21456492

In [8]:
ids = pd.read_csv('cafe1.csv')['0'].values
ids = list(ids)
ids = ids[0:101]

In [108]:
cafe_id.iloc[441:882]

     Unnamed: 0           0
441         441   169198683
442         442    19392070
443         443  1061357752
444         444  1770500852
445         445  2146177384
..          ...         ...
877         877  1464507406
878         878  1098065316
879         879   893051750
880         880    20196364
881         881    21160031

[441 rows x 2 columns]

In [14]:
ids = [
   '13615194',  '890539012',  '712442596','1704706310',   '22854241',
        '182270139'
]

In [ ]:
# menus

In [9]:
import time 
cafes = []
menus = []
comments = []
keywords = []
for id in ids:
    time.sleep(3)
    res = requests.get(f'https://place.map.kakao.com/main/v/{id}')
    data = res.json()
    name = data['basicInfo']['placenamefull']
    cafes.append({
        'id': id,
        'name': name,
        #'image_url': data['basicInfo']['mainphotourl'],
    })
    if 'metaKeywordList' in data['basicInfo']: #키워드가 있을 때 
        for keyword in data['basicInfo']['metaKeywordList']:
            keywords.append({
                'cafe_id': id,
                'cafe': name,
                'keyword' : keyword
            })
# print(data)
pd.DataFrame(keywords)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [38]:
cafes = []
menus = []
comments = []
address = []

for id in ids:
    res = requests.get(f'https://place.map.kakao.com/main/v/{id}')
    data = res.json()
    cafes.append({
        'cafe_id': id,
        'cafe': data['basicInfo']['placenamefull'],
        'address': data['basicInfo']['address']['region'].get('fullname',''),
        'addrbunho' : data['basicInfo']['address']['addrbunho'],
        'image_url': data['basicInfo'].get('mainphotourl', ''),
    })

pd.DataFrame(cafes)

,cafe_id,cafe,address,addrbunho,image_url
0,13615194,스토리온,제주특별자치도 제주시 한경면 저지리,2120-174,http://t1.daumcdn.net/cfile/214D9F3A57BA9FAC2E
1,890539012,아이올라,제주특별자치도 제주시 삼도1동,529-7,
2,712442596,라꾸르카페펜션,제주특별자치도 제주시 애월읍 하가리,960-1,

In [34]:
cafes = []
menus = []
comments = []

for id in ids:
    time.sleep(3)
    res = requests.get(f'https://place.map.kakao.com/main/v/{id}')
    data = res.json()
    cafes.append({
        'id': id,
        'name': data['basicInfo']['placenamefull'],
        #'image_url': data['basicInfo']['mainphotourl'],
    })
    # menu
    if 'menuInfo' in data:
        for menu in data['menuInfo']['menuList']:
            menus.append({
                'cafe_id': id,
                'cafe': data['basicInfo']['placenamefull'],
                'name': menu['menu'],
                'price': menu['price']
            })

pd.DataFrame(menus)

Empty DataFrame
Columns: []
Index: []

### 수정 ( 이 아래부터는 아닙니다~!)
- image

In [6]:
from math import ceil

import requests
from bs4 import BeautifulSoup

cafes = []
menus = []
comments = []

for id in ids:
    res = requests.get(f'https://place.map.kakao.com/main/v/{id}')
    data = res.json()
    cafes.append({
        'cafe_id': id,
        'name': data['basicInfo']['placenamefull'],
        'image_url': data['basicInfo']['mainphotourl']
    })

pd.DataFrame(cafes)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

File 읽기: <https://docs.python.org/ko/3/tutorial/inputoutput.html>

JSON 파싱: <https://docs.python.org/ko/3/library/json.html>

In [3]:
# 카페 IDs
ids = pd.read_csv('cafe1.csv')['0'].values
ids = ids[1364:2048] #63개까지만 됨.

pd.DataFrame(ids)

              0
0      11877497
1    1263620627
2     368243275
3    1571310600
4      13571332
..          ...
679    21525863
680  1001060560
681    21542799
682  1436399988
683   356575987

[684 rows x 1 columns]

In [4]:


import json


# 카페 IDs
# ids = pd.read_csv('cafe1.csv')['0'].values #카페 아이디의 ['0']칼럼의 values 불러오기
# ids = ids[1364:2048] #내가 맡은 부분 자르기 
# # 이 두 ids 줄을 dawnlodad.py에 넣어줘야 합니당! 
# # pd.DataFrame(ids)

cafes = []
menus = []
comments = []
keywords = []
# 내가 원하는거! 카페 아이디별로해서(이미 위에 카페 아이디만 모아놓은 리스트가 존재) 여기의 메타키워드 정보를 뽑고 싶음) 
for id in ids[:402]:
    with open(f'data/{id}.json') as f:  #json 파일 저장한 곳이 data/폴더여서 이름이 이렇게 나와요! 이부분만 수정하구 #id 하나 잡아서 돌리면 됩니다. 
        data = json.load(f)
    name = data['basicInfo']['placenamefull']
    cafes.append({
        'cafe_id': id,
        'name': name,
    })
    # keywords
    if 'metaKeywordList' in data['basicInfo']: #키워드가 있을 때 
        for keyword in data['basicInfo']['metaKeywordList']:
            keywords.append({
                'cafe_id': id,
                'cafe': name,
                'keyword' : keyword
            })
# print(data)
pd.DataFrame(keywords)

        cafe_id            cafe  keyword
0      23933670        커피가게쉬고가게  핸드드립전문점
1     484703392         바라나시책골목      북카페
2    1874740851          베베맘이유식    수제이유식
3    1874740851          베베맘이유식    이유식카페
4     392583573  심심푸리만화카페 제주외도점    데이트코스
..          ...             ...      ...
124  1362051346           카페이호동   빈티지분위기
125    27537304      엘가커피 제주연동점    로스팅전문
126  1604142577           부러워커피    로스팅전문
127  1604142577           부러워커피    아기자기한
128    24506425           카페바라기     아침식사

[129 rows x 3 columns]

In [65]:
pd.DataFrame(keywords).to_csv('kewords1.csv')

In [70]:


import json


# 카페 IDs
# ids = pd.read_csv('cafe1.csv')['0'].values #카페 아이디의 ['0']칼럼의 values 불러오기
# ids = ids[1364:2048] #내가 맡은 부분 자르기 
# # 이 두 ids 줄을 dawnlodad.py에 넣어줘야 합니당! 
# # pd.DataFrame(ids)

cafes = []
menus = []
comments = []
keywords = []
# 내가 원하는거! 카페 아이디별로해서(이미 위에 카페 아이디만 모아놓은 리스트가 존재) 여기의 메타키워드 정보를 뽑고 싶음) 
for id in ids[403:668]:
    with open(f'data/{id}.json') as f:  #json 파일 저장한 곳이 data/폴더여서 이름이 이렇게 나와요! 이부분만 수정하구 #id 하나 잡아서 돌리면 됩니다. 
        data = json.load(f)
    name = data['basicInfo']['placenamefull']
    cafes.append({
        'cafe_id': id,
        'name': name,
    })
    # keywords
    if 'metaKeywordList' in data['basicInfo']: #키워드가 있을 때 
        for keyword in data['basicInfo']['metaKeywordList']:
            keywords.append({
                'cafe_id': id,
                'cafe': name,
                'keyword' : keyword
            })
# print(data)
pd.DataFrame(keywords)

        cafe_id            cafe keyword
0      27391688  플레이케이팝 별이빛나는밤에   데이트코스
1     788239844           잼잼팩토리   분위기좋은
2     788239844           잼잼팩토리   아기자기한
3     788239844           잼잼팩토리  캠핑느낌나는
4     788239844           잼잼팩토리    힐링카페
..          ...             ...     ...
100   193625605          어제보다오늘   오션뷰카페
101   193625605          어제보다오늘    전망좋은
102    18143017     스타벅스 성산일출봉점    아침식사
103  1368243224          바이티티카카   브런치카페
104   615988591            식빵가게   수제케이크

[105 rows x 3 columns]

In [71]:
pd.DataFrame(keywords).to_csv('kewords2.csv')

In [72]:


import json


# 카페 IDs
# ids = pd.read_csv('cafe1.csv')['0'].values #카페 아이디의 ['0']칼럼의 values 불러오기
# ids = ids[1364:2048] #내가 맡은 부분 자르기 
# # 이 두 ids 줄을 dawnlodad.py에 넣어줘야 합니당! 
# # pd.DataFrame(ids)

cafes = []
menus = []
comments = []
keywords = []
# 내가 원하는거! 카페 아이디별로해서(이미 위에 카페 아이디만 모아놓은 리스트가 존재) 여기의 메타키워드 정보를 뽑고 싶음) 
for id in ids[669:]:
    with open(f'data/{id}.json') as f:  #json 파일 저장한 곳이 data/폴더여서 이름이 이렇게 나와요! 이부분만 수정하구 #id 하나 잡아서 돌리면 됩니다. 
        data = json.load(f)
    name = data['basicInfo']['placenamefull']
    cafes.append({
        'cafe_id': id,
        'name': name,
    })
    # keywords
    if 'metaKeywordList' in data['basicInfo']: #키워드가 있을 때 
        for keyword in data['basicInfo']['metaKeywordList']:
            keywords.append({
                'cafe_id': id,
                'cafe': name,
                'keyword' : keyword
            })
# print(data)
pd.DataFrame(keywords)

      cafe_id  cafe  keyword
0  1660120281  유노이아    디저트카페
1  1660120281  유노이아   베이킹클래스
2  1660120281  유노이아   플라워클래스
3    14500376  이츠커피    로스팅전문
4    14500376  이츠커피    분위기좋은
5    14500376  이츠커피    야외테라스
6    14500376  이츠커피  핸드드립전문점
7   356575987  수망일기    분위기좋은

In [76]:
pd.DataFrame(keywords).to_csv('kewords3.csv')

In [78]:
k1 = pd.read_csv('kewords1.csv')
k2 = pd.read_csv('kewords2.csv')
k3 = pd.read_csv('kewords3.csv')

In [85]:
kewords_ye = pd.concat([k1,k2,k3])
del kewords_ye['Unnamed: 0']

In [86]:
kewords_ye.head()

      cafe_id            cafe  keyword
0    23933670        커피가게쉬고가게  핸드드립전문점
1   484703392         바라나시책골목      북카페
2  1874740851          베베맘이유식    수제이유식
3  1874740851          베베맘이유식    이유식카페
4   392583573  심심푸리만화카페 제주외도점    데이트코스

In [87]:
kewords_ye.to_csv('kewords_ye.csv')

In [84]:


import json


# 카페 IDs
# ids = pd.read_csv('cafe1.csv')['0'].values #카페 아이디의 ['0']칼럼의 values 불러오기
# ids = ids[1364:2048] #내가 맡은 부분 자르기 
# # 이 두 ids 줄을 dawnlodad.py에 넣어줘야 합니당! 
# # pd.DataFrame(ids)

cafes = []
menus = []
comments = []
bus = []
# 내가 원하는거! 카페 아이디별로해서(이미 위에 카페 아이디만 모아놓은 리스트가 존재) 여기의 메타키워드 정보를 뽑고 싶음) 
for id in ids[:402]:
    with open(f'data/{id}.json') as f:  #json 파일 저장한 곳이 data/폴더여서 이름이 이렇게 나와요! 이부분만 수정하구 #id 하나 잡아서 돌리면 됩니다. 
        data = json.load(f)
    name = data['basicInfo']['placenamefull']
    cafes.append({
        'cafe_id': id,
        'name': name,
    })
    # keywords
    if 'metaKeywordList' in data['basicInfo']: #키워드가 있을 때 
        for keyword in data['basicInfo']['metaKeywordList']:
            keywords.append({
                'cafe_id': id,
                'cafe': name,
                'keyword' : keyword
            })
# print(data)
pd.DataFrame(keywords)

KeyError: 'openHour'

In [ ]:
cafes = []
menus = []
comments = []


ids = ['id를 넣어주세요']
# 내가 원하는거! 카페 아이디별로해서(이미 위에 카페 아이디만 모아놓은 리스트가 존재) 여기의 메타키워드 정보를 뽑고 싶음) 
for id in ids:
    with open(f'data/{id}.json') as f:  #json 파일 저장한 곳이 data/폴더여서 이름이 이렇게 나와요! 이부분만 수정하구 #id 하나 잡아서 돌리면 됩니다. 
        data = json.load(f)
    name = data['basicInfo']['placenamefull']
    cafes.append({
        'cafe_id': id,
        'name': name,
    })
    # keywords
    if 'opdenHour' in data['basicInfo']: #키워드가 있을 때 
        for keyword in data['basicInfo']['metaKeywordList']:
            keywords.append({
                'cafe_id': id,
                'cafe': name,
                'keyword' : keyword
            })
# print(data)
pd.DataFrame(cafes)

print(housrs)

In [23]:
from math import ceil

import requests
from bs4 import BeautifulSoup

cafes = []
menus = []
comments = []

for id in ids:
    res = requests.get(f'https://place.map.kakao.com/main/v/{id}')
    data = res.json()
    cafes.append({
        'cafe_id': id,
        'name': data['basicInfo']['placenamefull'],
        'image_url': data['basicInfo']['mainphotourl']
    })

pd.DataFrame(cafes)

           id  name                                          image_url
0    26094495   까미노  http://t1.daumcdn.net/place/827554C11BDE4BC5BA...
1   819891458  시루애월  http://t1.daumcdn.net/localfiy/176E70BB7DD94CF...
2  1852395758  사계생활  http://t1.daumcdn.net/place/26F940FB5C89438E9F...

In [ ]:
# 리뷰 평점

In [29]:
from math import ceil

import requests
from bs4 import BeautifulSoup

cafes = []
menus = []
comments = []

    # comment
    
for id in ids:
    res = requests.get(f'https://place.map.kakao.com/main/v/{id}')
    data = res.json()
    for page in range(1, ceil(data['comment']['allComntcnt'] / 5) + 1):
        res = requests.get(f'https://place.map.kakao.com/commentlist/v/{id}/{page}')
        data = res.json()
        for comment in data['comment']['list']:
            comments.append({
                'cafe_id': id,
                'user_id': comment.get('commentid',''),
                'message': comment.get('contents', ''),
                'point': comment.get('point', '')
                })

pd.DataFrame(comments)

,cafe_id,user_id,message,point
0,26094495,1209010,까미노..\n차와 빵좀 아는 사장님이네요~\n플루트빵도 맛나고 커피 좋아요\n포르뚜...,5
1,26094495,1132395,인케리어 찡,5
2,26094495,1124998,바다 실컷 본 후 이곳에서 초록색 풀과 오름 바라보며 좋았음. 밀크티는 맛있지만 개...,5
3,26094495,1059789,분위기 뷰 일단 너무 좋고요\n비오는날 왔는데 한적하니 힐링되네요\n멀리 바다도 보...,5
4,26094495,1050100,사장님들이 넘 친절해요. 집에 온 듯한 친절함과 편안함이에요. 분위기도 좋구요.,5
5,26094495,877009,사장님이 너무 친절하시고 이쁜 카페였어요. 야외자리가 정말 맘에 들었어요. 다음에도...,5
6,26094495,547604,공간이 분리되어있어서 조용히 있다 가기 좋았다 산미있는 에티오피아 아메리카노도 좋았...,3
7,26094495,493004,이 곳 분위기를 참 좋아합니다. 친절하시고요. 그런 분들이 만드신 빵과 음료이니 믿...,5
8,26094495,475089,인테리어와 외부 풍경. 커피 맛도!,4
9,26094495,468090,"사장님의 여유로움과 멋진 철학이 담긴 카페, 강추!",5
10,26094495,453073,예뻐요 카페 정말 예쁘구 예쁜거에 별 하나 플랫 화이트 맛있어서 별하나 당근 케이크...,3
11,26094495,426386,다 좋아요 그냥,5
12,26094495,280930,아늑하구 맛있고 쉬기 좋아요,5
13,26094495,276632,"커피도 맛있고, 분위기도 좋고, 무엇보다 다른 곳에서 맛볼수 없는 커피들이 있어요....",5
14,26094495,243729,계속 있고싶은 곳,5
15,26094495,775354,사진으로 담을수 없는 풍경의 카페,5
16,26094495,242927,,2
17,26094495,188553,,5
18,26094495,124798,아모르코코? 초코라떼랑 바닐라라떼 먹엇는데 맛있었어요,5
19,26094495,112905,치즈케이크. 아인슈페너 먹었어요\n치즈케익은 부드럽고 맛남\n아인슈페너 크림은 맛있...,3
20,26094495,68674,인테리어 좋고 커피도 맛있어요,5
21,26094495,711994,Coffee,3
22,26094495,35985,사모님 커피 설명 엣지있게 해주시구 친절하세용\n조용한 분위기에 햇살 받으며 잘 쉬...,5
23,26094495,2533,크하\n커피\n크레마\n크~인테리어,5
24,26094495,827641,,3
25,26094495,628165,,3
26,26094495,331656,최고에요\n바닷가뷰 카페들 겉모습만 멀쩡하고\n커피나 음식 퀄리티가 너무 구린데\n...,5
27,26094495,1266834,,5
28,26094495,950442,조용하고 너무좋음 비올때 더좋을듯,5
29,26094495,633075,,4
...,...,...,...,...
56,26094495,713875,"커피맛도 좋고 주변 경관도 좋으나, 주말에는 약간 시끄러운편",4
57,26094495,50820,,4
58,26094495,268548,,4
59,26094495,732034,,0
60,26094495,713117,"살롱드라방이 토,일요일 닫는 바람에 가게 된 곳.\n우연히 찾은곳이 예뻐서 맘에 들...",4
61,26094495,6276,traveline 추천,0
62,26094495,615291,와우...넘 좋다~,0
63,26094495,737128,기약없는 기다림이란 건 \n참 힘든 것이라는 걸 -\n\n그래도 제주라서 다행이야\...,0
64,26094495,2210,"분위기 좋은 카페~~\n바다쪽은 아니지만 인테리어가 좋고, 주변 경관이 수려함~",0
65,26094495,726029,혼자 냠냠...,0
66,26094495,1642580,소문듣고 많이들 찾아오나 그럴 필요가 있는지 의문이 들었던 곳\n시골길에 있어 주차...,3
67,26094495,1479264,아메리카노와 포루뚜나가 너무 인상적인 곳,5
68,819891458,1057525,"이번에 여자친구랑 제주도 여행가게되면서 애월쪽 방문하다가 들렀는데, 인테리어도 괜찮...",5
69,819891458,559053,진짜 보는재미가 쏠쏠했습니다! 브런치도 너무 맛있고~~~ 또 가고싶네요,5
70,819891458,1240834,최악...\n불친절...\n\n가격대비 음식도 너무하네요...\n\n아기자기 소품 ...,1
71,819891458,1128404,넓직하고 맛있는 브런치.. 공간이 다 다른 느낌이라 사진을 어디서 찍어도 예쁘네요,5
72,819891458,1008932,"인스타를 즐겨하는 스타일이라 그런지, 인테리어를 많이 보게 되는데 여기는 인테리어 ...",5
73,819891458,916358,여기 한적하고 데이트하기에 진짜 좋아요!! 힐링되는 분위기! 편안하고 공기가 좋다고...,5
74,819891458,844146,조용하고 비오는날 창가자리 운치있어요 (&bull;̀ᴗ&bull;́)و,5
75,819891458,763066,정말 제주도 1년에 최소 2번 이상가는데 분위기 느낌 갑! 또가야지,5
76,819891458,476548,엔틱한 장식들이 많았고 맛있는 브런치와 따뜻한 분위기라 정말 좋았어요~ 커피도 쏘쏘...,5
77,819891458,411965,늦게까지 하는곳이 있어서 좋은데 참 불친절하시네요~~,3
78,819891458,372633,,5
79,819891458,352908,여기 좋은 카페 생겨서 너무 좋아요.,5
80,819891458,290567,ㅠㅠㅠㅠㅠㅠㅠㅠ 동네에 늦게까지 하는 카페 생겨서 너무 좋아요! 분위기두 너무 좋음,5
81,819891458,2025280,,5
82,1852395758,1197551,우연히 들린 가게. 전혀 커피 파는 곳인줄 몰랐어요.\n커피맛 좋구요 볼거리도 많네...,5
83,1852395758,1137683,마시는 즐거움에 보는 즐거움까지\n추천!!,5
84,1852395758,808001,컨셉 너무 재밌게 잘 잡았고 음료도 맛있음 ㅎㅎ,5
85,1852395758,545182,감동.. 너무 정갈하고 예뻐요 커피도 맛있음!,5

# 다 합친 버전

In [65]:
cafes = []
menus = []
comments = []

for id in ids:
    res = requests.get(f'https://place.map.kakao.com/main/v/{id}')
    data = res.json()
    cafes.append({
        'cafe_id': id,
        'cafe': data['basicInfo']['placenamefull'],
        'image_url': data['basicInfo']['mainphotourl'],
    })
    # menu
    if 'menuInfo' in data:
        for menu in data['menuInfo']['menuList']:
            menus.append({
                'cafe_id': id,
                'cafe': data['basicInfo']['placenamefull'],
                'name': menu['menu'],
                'price': menu['price'],
            })
    # comment
    for page in range(1, ceil(data['comment']['allComntcnt'] / 5) + 1):
        res = requests.get(f'https://place.map.kakao.com/commentlist/v/{id}/{page}')
        data = res.json()
        for comment in data['comment']['list']:
            comments.append({
                'cafe_id': id,
                'user_id': comment.get('commentid',''),
                'message': comment.get('contents', ''),
                'point': comment.get('point', '')
                })

            
            
            
pd.DataFrame(cafes)
pd.DataFrame(comments)
pd.DataFrame(menus)

      cafe_id  cafe          name  price
0    26094495   까미노       얼그레이 도르  8,000
1    26094495   까미노   까미노 아이스 밀크티  9,000
2    26094495   까미노        블루베리주스  8,000
3    26094495   까미노       블루베리스무디  8,000
4    26094495   까미노         생크림케익  6,500
5  1852395758  사계생활         아메리카노  4,500
6  1852395758  사계생활          카페라떼  5,000
7  1852395758  사계생활  산방카푸치노 (HOT)  5,500
8  1852395758  사계생활  돌담크림모카 (ICE)  6,000
9  1852395758  사계생활  제주말차라떼 (ICE)  6,000

### 수정

In [ ]:
pd.DataFrame(menus)

In [ ]:
pd.DataFrame(comments)

In [ ]:
 


#         for m,n in zip(data['comment']['list'], data['comment']['list']):
#             f.writerow((m.contents[0], n.contents[0]))

# soup = BeautifulSoup(res.content, 'html.parser')
# aria-hidden="true"



# for item in mydata:
#     print(item.get_text())

#mArticle > div.cont_evaluation > div.evaluation_review > ul > li:nth-child(1) > div.comment_info > p > span
    
# mArticle > div.cont_evaluation > div.evaluation_review > ul > li:nth-child(1) > div.comment_info > p

#     mArticle > div.cont_evaluation > div.evaluation_review > ul > li > div.comment_info > p

In [12]:
from math import ceil

import requests
from bs4 import BeautifulSoup

ids = [
    '26094495',
]

for id in ids:
    res = requests.get(f'https://place.map.kakao.com/main/v/{id}')
    data = res.json()
    for page in range(1, ceil(data['comment']['allComntcnt'] / 5) + 1):
        res = requests.get(f'https://place.map.kakao.com/commentlist/v/{id}/{page}')
        data = res.json()
        print(page, len(data['comment']['list']))
        for comment in data['comment']['list']:
            a = comment.get('contents', '')
            print()
        for comment in data['comment']['list']:
            print(comment.get('point', ''))
            print()



# soup = BeautifulSoup(res.content, 'html.parser')
# aria-hidden="true"



# for item in mydata:
#     print(item.get_text())

#mArticle > div.cont_evaluation > div.evaluation_review > ul > li:nth-child(1) > div.comment_info > p > span
    
# mArticle > div.cont_evaluation > div.evaluation_review > ul > li:nth-child(1) > div.comment_info > p

#     mArticle > div.cont_evaluation > div.evaluation_review > ul > li > div.comment_info > p

1 5





5

5

5

5

5

2 5





5

3

5

4

5

3 5





3

5

5

5

5

4 5





5

2

5

5

3

5 5





5

3

5

5

3

6 5





3

5

5

5

4

7 5





5

5

1

5

3

8 5





5

1

4

5

5

9 5





3

3

4

4

4

10 5





4

4

4

4

4

11 5





4

4

4

5

5

12 5





4

4

4

4

0

13 5





4

0

0

0

0

14 3



0

3

5

In [ ]:
a

In [ ]:
a

In [ ]:
import requests
from bs4 import BeautifulSoup

res = requests.get('https://place.map.kakao.com/26094495')
soup = BeautifulSoup(res.content, 'html.parser')
data = soup.select('#mArticle > div.cont_evaluation > div.evaluation_review')
data





#mArticle > div.cont_evaluation > div.evaluation_review

# for item in data:
#     print(item.get_text())
    

#     import requests
# from bs4 import BeautifulSoup

# res = requests.get('https://search.shopping.naver.com/best100v2/detail.nhn?catId=50000000')
# soup = BeautifulSoup(res.content, 'html.parser')
# data = soup.select('#productListArea > ul > li> p > a')
# for item in data:
#     print(item.get_text())